# Generated by Django 4.2.30 on 2026-04-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_alter_producto_options'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(db_column='id_venta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_column='fecha_venta')),
                ('total_venta', models.DecimalField(db_column='total_venta', decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='completada', max_length=50)),
                ('metodo_pago', models.CharField(default='efectivo', max_length=50)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='clientes.cliente')),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(db_column='id_detalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unit', models.DecimalField(db_column='precio_unit', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='productos.producto')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='carrito.venta')),
            ],
            options={
                'db_table': 'detalle_ventas',
                'managed': True,
            },
        ),
    ]
