# Generated by Django 4.2.29 on 2026-03-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(db_column='cantidad_stock', default=0)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('colores', models.CharField(blank=True, max_length=200, null=True)),
                ('tallas', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_anterior', models.DecimalField(blank=True, db_column='precioAnterior', decimal_places=2, max_digits=12, null=True)),
                ('es_nuevo', models.BooleanField(db_column='esNuevo', default=False)),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
    ]
