-- ============================================================
-- Script de migración: SQLite → PostgreSQL
-- Proyecto: Oksumoda Django
-- Generado automáticamente
-- ============================================================

-- Desactivar checks de FK temporalmente
SET session_replication_role = replica;

-- ROLES
TRUNCATE TABLE roles RESTART IDENTITY CASCADE;
INSERT INTO roles (id_rol, nombre) VALUES (1, 'ADMIN');
INSERT INTO roles (id_rol, nombre) VALUES (2, 'CLIENTE');
SELECT setval('roles_id_rol_seq', (SELECT MAX(id_rol) FROM roles));

-- CATEGORIAS
TRUNCATE TABLE categorias RESTART IDENTITY CASCADE;
INSERT INTO categorias (id_categoria, nombre) VALUES (1, 'Hombres');
INSERT INTO categorias (id_categoria, nombre) VALUES (2, 'Mujeres');
INSERT INTO categorias (id_categoria, nombre) VALUES (3, 'Niños');
INSERT INTO categorias (id_categoria, nombre) VALUES (4, 'Otros');
SELECT setval('categorias_id_categoria_seq', (SELECT MAX(id_categoria) FROM categorias));

-- PRODUCTOS (161 registros)
TRUNCATE TABLE productos RESTART IDENTITY CASCADE;
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (7, 'Jean Negro', 'Vaquero de cinco bolsillos confeccionado en denim de algodón rígido. Diseño de tiro medio con cierre de botones y perneras rectas. Ofrece un ajuste relajado desde la cadera hasta el bajo, con una pernera más amplia a partir del muslo. Un básico atemporal que nunca pasa de moda.
', '50819b124cccab48d47a898bb68f6b60d9a07aa0.jpg', 'activo', 120, 11, 'Hombres', 'Pantalones', 'Negro', 'XS, S, M, L, XL, XXL', 150, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (8, 'Jean Azul Denim Oscuro', 'Jean de cinco bolsillos elaborado en denim de algodón rígido. Cuenta con tiro medio y cierre de botones, además de perneras rectas. Su diseño ofrece un ajuste cómodo y relajado desde la cadera hasta el bajo, con mayor amplitud en el muslo. Una prenda clásica que nunca pasa de moda.
', '5e142650ae0be69e48f65c0f575def93ff3b98b2.avif', 'activo', 119.9, 12, 'Hombres', 'Pantalones', 'Azul denim oscuro, Liso', 'XS, S, M, L, XL, XXL', 149.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (9, 'Jean Azul Denim Claro', 'Jean de cinco bolsillos confeccionado en denim de algodón rígido. Presenta tiro medio con cierre de botones y perneras rectas. Su corte es relajado desde la cadera hasta el bajo, con mayor amplitud a partir del muslo. Un básico atemporal que nunca pasa de moda.', 'ac7a655bdbe1f794d41eca9835033c2ce3abe6c0.avif', 'activo', 99.9, 28, 'Hombres', 'Pantalones', 'Azul denim claro, Liso', 'XS, S, M, L, XL, XXL', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (10, 'Jean Crema', 'Jean de cinco bolsillos confeccionado en denim de algodón rígido. Cuenta con tiro medio, cierre de botones y perneras rectas. Su corte es relajado desde la cadera hasta el bajo, con mayor amplitud a partir del muslo. Un básico atemporal que nunca pasa de moda.
', 'f8e07387cb9e04c685ff6c35e7e5df55697b0be0.avif', 'activo', 124.9, 38, 'Hombres', 'Pantalones', 'Crema, Liso', 'XS, S, M, L, XL, XXL', 159.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (11, 'Jean Azul Denim Oscuro', 'Jean de cinco bolsillos en denim de algodón rígido, con corte holgado desde la cadera hasta el bajo y perneras anchas. Tiro caído, cintura estándar y cierre de cremallera. Una prenda cómoda y moderna que destaca por su estilo relajado.', '37e46dca98d64a8072d895495ec108fb0331893a.avif', 'activo', 129.9, 30, 'Hombres', 'Pantalones', 'Azul denim oscuro, Liso', 'XS, S, M, L, XL, XXL', 169.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (12, 'Jean Azul Denim Oscuro', 'Jean de cinco bolsillos en denim de algodón rígido, con corte holgado de cadera a bajo y perneras extraanchas con pliegues en el tobillo. Tiro bajo, cintura estándar y cierre de cremallera. Una prenda ideal para lograr un look denim moderno e impactante.', '93839d2be58e54abe9cca2385c19fc0e95d7f69b.avif', 'activo', 134.9, 34, 'Hombres', 'Pantalones', 'Azul denim oscuro, Liso', 'XS, S, M, L, XL, XXL', 179.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (13, 'Jean Gris Denim Medio', 'Vaquero de cinco bolsillos confeccionado en denim de algodón rígido. Presenta un corte holgado desde la cadera hasta el bajo, con perneras redondeadas y extraanchas, rematadas con pliegues en el tobillo. Tiro bajo, cintura estándar y cierre de cremallera. Una prenda que representa la perfección en clave denim.', 'a014d7663dffdeba4e39ad787aeaf31eee940834.avif', 'inactivo', 139.9, 29, 'Hombres', 'Pantalones', 'Gris denim medio, Liso', 'XS, S, M, L, XL, XXL', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (14, 'Jean Azul Denim Pálido', 'Jean de cinco bolsillos en denim de algodón rígido, con corte holgado desde la cadera hasta el bajo y perneras extraanchas y redondeadas con pliegues en el tobillo. Tiro bajo, cintura estándar y cierre de cremallera. Una prenda que combina comodidad y estilo para un look denim impecable.', '51de65356b6f0492e1ccee9b0400764fdbd5b364.avif', 'inactivo', 144.9, 31, 'Hombres', 'Pantalones', 'Azul denim pálido, Liso', 'XS, S, M, L, XL, XXL', 194.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (15, 'Jean Gris Claro', 'Jean de cinco bolsillos en denim de algodón rígido, con corte holgado desde la cadera hasta el bajo y perneras extraanchas y redondeadas con pliegues en el tobillo. Tiro bajo, cintura estándar y cierre de cremallera. Una prenda que combina estilo y comodidad para un look denim perfecto.', '85882b6aa9090f0324e7a6dcf0e3fe17604f0388.avif', 'activo', 149.9, 33, 'Hombres', 'Pantalones', 'Gris claro, Liso', 'XS, S, M, L, XL, XXL', 199.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (16, 'Jean Beige', 'Jean de cinco bolsillos en denim de algodón rígido, con corte holgado desde la cadera hasta el bajo y perneras redondeadas extraanchas con pliegues en el tobillo. Tiro bajo, cintura estándar y cierre de cremallera. La prenda ideal para lograr un look denim moderno e impactante.', '0982db5eeedc90b586f4f35577ffa5e557a0cb7a.avif', 'activo', 154.9, 33, 'Hombres', 'Pantalones', 'Beige/Azul', 'XS, S, M, L, XL, XXL', 204.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (17, 'Jean Rosa', 'Jean de cinco bolsillos en denim de algodón rígido con detalles maxidesgastados en la parte delantera. Corte holgado desde la cadera hasta el bajo con pernera recta amplia y tiro caído. Cintura estándar y cierre de cremallera. Una prenda diseñada para destacar y conquistar con estilo.', '3fff5040677b276c7825e4f134b3dee97889da19.avif', 'activo', 159.9, 29, 'Hombres', 'Pantalones', 'Rosa, Liso', 'XS, S, M, L, XL, XXL', 214.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (18, 'Jean Azul Denim Empolvado', 'Jean de cinco bolsillos confeccionado en denim de algodón rígido, con corte holgado de cadera a bajo y pernera redondeada amplia. Incluye pinzas en las rodillas para aportar volumen, tiro caído, cintura estándar con cierre de cremallera y pliegues al final de la pernera. Una prenda que combina comodidad y estilo con un toque moderno.
', '07ff554bb68ef8d06af14959ada1a0f16c3c2c13.avif', 'activo', 164.9, 31, 'Hombres', 'Pantalones', 'Azul denim empolvado, Liso', 'XS, S, M, L, XL, XXL', 224.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (19, 'Jean Gris Denim', 'Jean de cinco bolsillos en denim de algodón rígido, con corte holgado desde la cadera hasta el bajo y perneras redondeadas extra anchas con pliegues en el tobillo. Tiro bajo, cintura estándar y cierre de cremallera. Una prenda ideal para lograr un look denim moderno e impactante.', '2a05650df5a5f6fd41eb2df56a2db0a6ed6c602c.avif', 'activo', 169.9, 13, 'Hombres', 'Pantalones', 'Gris denim, Liso', 'XS, S, M, L, XL, XXL', 229.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (20, 'Jean Beige Oscuro', 'Jean de cinco bolsillos en denim de algodón rígido, con corte holgado desde la cadera hasta el bajo y pernera redondeada amplia. Presenta pinzas en las rodillas que aportan volumen, tiro caído, cintura estándar con cierre de cremallera y pliegues en el tobillo. Una prenda cómoda y moderna, ideal para destacar con un look denim único.', '61e67989d62f016f0825e6a10ce6d1b327b5067c.avif', 'activo', 174.9, 34, 'Hombres', 'Pantalones', 'Beige oscuro, Liso', 'XS, S, M, L, XL, XXL', 234.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (21, 'Jean Verde Denim', 'Jean de cinco bolsillos en denim de algodón rígido, con corte holgado desde la cadera hasta el bajo y perneras extraanchas con pliegues en el tobillo. Tiro bajo, cintura estándar y cierre de cremallera. Una prenda que combina estilo y comodidad, perfecta para un look denim impecable.', '8fbca9709ad558d2bce7578df3206c858b505234.avif', 'activo', 179.9, 14, 'Hombres', 'Pantalones', 'Verde denim', 'XS, S, M, L, XL, XXL', 239.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (22, 'Camiseta Blanco', 'Camiseta de corte ajustado en punto suave de algodón pima. Cuello redondo ribeteado en canalé fino y bajo recto.

', '4487829bb5714122079e8f8bdc08be7f990d1d2b.avif', 'activo', 64.9, 15, 'Hombres', 'Camisetas', 'Blanco, Liso', 'XS, S, M, L, XL, XXL', 89.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (23, 'Camiseta Negro', 'Camiseta de corte ajustado en punto suave de algodón pima. Cuello redondo ribeteado en canalé fino y bajo recto.

', '7cfa9be6554e6a7263e60cbe8f69d501573b96c8.avif', 'activo', 69.9, 11, 'Hombres', 'Camisetas', 'Negro, Liso', 'XS, S, M, L, XL, XXL', 94.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (24, 'Camiseta Azul Marino', 'Camiseta de corte ajustado en punto suave de algodón pima. Cuello redondo ribeteado en canalé fino y bajo recto.

', 'd1d5362a3ba853f48b5473c8279127b8c4cdca04.avif', 'activo', 72.9, 12, 'Hombres', 'Camisetas', 'Azul marino, Liso', 'XS, S, M, L, XL, XXL', 99.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (25, 'Camiseta Marrón Oscuro', 'Camiseta de corte ajustado en punto suave de algodón pima. Cuello redondo ribeteado en canalé fino y bajo recto.

', '75f56a7b3ddbb760381e50707a50bc7f78841650.avif', 'activo', 74.9, 14, 'Hombres', 'Camisetas', 'Marrón oscuro, Liso', 'XS, S, M, L, XL, XXL', 104.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (26, 'Camiseta Blanco', 'Camiseta en punto suave con cuello redondo ribeteado y bajo recto. Corte ajustado que realza el contorno del cuerpo creando una silueta entallada.

', '91fbdf86b951c137760adf2988383ee084483542.avif', 'activo', 76.9, 13, 'Hombres', 'Camisetas', 'Blanco, Liso', 'XS, S, M, L, XL, XXL', 109.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (27, 'Camiseta Beige Claro', 'Camiseta en punto de canalé suave de viscosa con cuello redondo. Corte estándar para una silueta clásica y cómoda.

', '0c4f153c917b7b060849e97e6b4951a84685eebf.avif', 'activo', 79.9, 14, 'Hombres', 'Camisetas', 'Beige claro, Liso', 'XS, S, M, L, XL, XXL', 114.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (28, 'Camiseta Beige', 'Camiseta en punto de algodón de peso medio. Modelo con cuello redondo ribeteado, hombros caídos y bajo recto. Corte relajado para una silueta casual pero no oversize.

', 'f9b4062422b1f58f4f054e67db507566f59e6f3e.avif', 'activo', 82.9, 11, 'Hombres', 'Camisetas', 'Beige, Liso', 'XS, S, M, L, XL, XXL', 119.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (29, 'Camiseta Verde Bosque', 'Camiseta en punto de algodón de peso medio. Modelo con cuello redondo ribeteado, hombros caídos y bajo recto. Corte relajado para una silueta casual pero no oversize.

', '3257dbd1c826db7686f75bc790681cb27db44095.avif', 'activo', 85.9, 15, 'Hombres', 'Camisetas', 'Verde bosque, Liso', 'XS, S, M, L, XL, XXL', 124.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (30, 'Camiseta Rosa', 'Camiseta en punto de algodón de peso medio. Modelo con cuello redondo ribeteado, hombros caídos y bajo recto. Corte relajado para una silueta casual pero no oversize.

', '4ce4b073af4cda0e85ba4ad0663581664d36e6dd.avif', 'activo', 88.9, 17, 'Hombres', 'Camisetas', 'Rosa, Liso', 'XS, S, M, L, XL, XXL', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (31, 'Camiseta Blanco', 'Camiseta en punto de algodón de peso medio con motivo estampado. Modelo con cuello redondo ribeteado, hombros caídos y bajo recto. Corte holgado para una silueta amplia pero no oversize.

', '40c32894b5aa4d1cb1fb3f985057986a1ad16fb2.avif', 'activo', 92.9, 16, 'Hombres', 'Camisetas', 'Blanco/Turquesa', 'XS, S, M, L, XL, XXL', 134.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (32, 'Camiseta Azul Claro', 'Camiseta en punto de algodón de peso medio con motivo estampado. Modelo con cuello redondo ribeteado, hombros caídos y bajo recto. Corte holgado para una silueta amplia pero no oversize.

', '160960ddc9730e3763c4ecc57bebdd873a686b26.avif', 'activo', 95.9, 12, 'Hombres', 'Camisetas', 'Azul claro', 'XS, S, M, L, XL, XXL', 139.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (33, 'Camiseta Burdeos', 'Camiseta boxy en punto ligero de algodón con motivos estampados. Modelo de hombros caídos con cuello redondo en canalé y bajo recto. Corte holgado para una silueta amplia pero no oversize.

', 'f6c038f5b0c6920d695d7aa8f98e36927d25a71e.avif', 'activo', 98.9, 16, 'Hombres', 'Camisetas', 'Burdeos/Blanco', 'XS, S, M, L, XL, XXL', 144.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (34, 'Chaquetas Burdeos', 'Cazadora ligeramente acolchada con cuello inglés y botones de presión delante. Bolsillos delanteros y un bolsillo interior, todos insertados. Elástico revestido en puños y bajo. Forro guateado.

', '3644fc7f4f2c8aa9822f9840511832e6205d6ff5.avif', 'activo', 189.9, 19, 'Hombres', 'Chaquetas', 'Burdeos, Liso', 'XS, S, M, L, XL, XXL', 259.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (35, 'Chaquetas Azul Oscuro', 'Cazadora ligeramente acolchada con cuello inglés y botones de presión delante. Bolsillos delanteros y un bolsillo interior, todos insertados. Elástico revestido en puños y bajo. Forro guateado.

', '77d22a93ca29758240b1bd0e7a094714b77800de.avif', 'activo', 199.9, 26, 'Hombres', 'Chaquetas', 'Azul oscuro, Liso', 'XS, S, M, L, XL, XXL', 269.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (36, 'Chaquetas Verde Caqui', 'Cazadora en tejido revestido con cuello y cremallera delante. Modelo con bolsillos laterales insertados, cremallera en los puños y elástico fruncido en el bajo.

', 'a2aa25afdcb784e618d3fce2bc446ca1a7e93a83.avif', 'activo', 214.9, 29, 'Hombres', 'Chaquetas', 'Verde caqui, Liso', 'XS, S, M, L, XL, XXL', 289.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (37, 'Chaquetas Topo Oscuro', 'Cazadora bomber ligeramente acolchada en nailon ligero, con cuello de peluche y cierre delantero con cremallera. Cuenta con bolsillo con cremallera en la manga, bolsillos laterales con solapa y botón de presión oculto, y un bolsillo interior con botón de presión. Remates acanalados anchos en puños y bajo, corte holgado que crea una silueta amplia sin ser oversize, y forro completo para mayor comodidad y calidez.', '36237157b3ae1c49eeb14e73f38f4572669cc7df.avif', 'activo', 229.9, 21, 'Hombres', 'Chaquetas', 'Topo oscuro, Liso', 'XS, S, M, L, XL, XXL', 309.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (38, 'Chaquetas Negro', 'Cazadora bomber ligeramente acolchada en nailon ligero con efecto lavado, con cuello y cierre delantero de cremallera. Incluye bolsillo con cremallera en la manga, bolsillos delanteros de parche con solapa y botón de presión, y bolsillo interior insertado con botón de presión oculto. Puños y bajo con elástico revestido y forro completo, combinando estilo moderno, funcionalidad y comodidad.
', 'f54ee1cdbcf246f0b58a38184e3af7cad0779d40.avif', 'activo', 189.9, 20, 'Hombres', 'Chaquetas', 'Negro, Liso', 'XS, S, M, L, XL, XXL', 149.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (39, 'Chaquetas Beige Empolvado', 'Cazadora bomber ligeramente acolchada en nailon, con cuello elevado de canalé y cierre delantero con cremallera. Incluye bolsillos insertados al bies con botón de presión, bolsillo con cremallera en la manga y dos bolsillos interiores con botón de presión. Remates acanalados anchos en puños y bajo. Forro completo para mayor comodidad y abrigo.', 'e2a4c45def96b2bbe5b1a730c919ac5d00fe8ae0.avif', 'activo', 199.9, 25, 'Hombres', 'Chaquetas', 'Beige empolvado, Liso', 'XS, S, M, L, XL, XXL', 249.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (40, 'Chaquetas Marrón Oscuro', 'Cazadora en piel suave, con cuello, cierre de cremallera y solapa cortavientos con dos botones de presión visibles. Hombros caídos, bolsillos delanteros de parche con solapa y botón de presión, y bolsillos calientamanos en la parte posterior. Canesú en la espalda y elástico fruncido en puños y bajo. Forrada para mayor comodidad y abrigo.', 'ab29586fab912c76b888c7b4d1810d7990397388.avif', 'activo', 279.9, 36, 'Hombres', 'Chaquetas', 'Marrón oscuro, Liso', 'XS, S, M, L, XL, XXL', 219.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (41, 'Chaquetas Azul Marino', 'Cazadora bomber en nailon fresco con cuello y cremallera delante. Bolsillo con cremallera en una manga, bolsillos delanteros de parche con solapa y botón de presión, y un bolsillo interior insertado con botón de presión oculto. Elástico fruncido en puños y bajo. Forrada.

', '7aff1d36a6b0bbceab613e5d4a898efaad0e81e4.avif', 'activo', 199.9, 22, 'Hombres', 'Chaquetas', 'Azul marino, Liso', 'XS, S, M, L, XL, XXL', 149.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (49, 'Calzado Castaño', 'Zapatos Oxford impermeables de última generación, ideales tanto para la oficina como para el fin de semana. Parte superior de piel Timberland resistente al agua, cordones de algodón, forro ecológico con 50% de plástico reciclado y plantilla viscoelástica Ortholite que se adapta al pie. Entresuela de EVA de alta amortiguación y suela de goma para durabilidad y tracción. Costuras selladas para evitar filtraciones de agua.', '51-zsMTeHZL._AC_SY575_.jpg', 'activo', 419.3, 13, 'Hombres', 'Calzado', 'Castaño', '38, 39, 40, 41, 42', 268.36, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (50, 'Calzado Beige', 'Zapatillas casuales de hombre, frescas, ligeras y cómodas para uso diario. Parte superior de microfibra de 1,2 mm con perforaciones que mejora la ventilación y absorbe la humedad. Puntera espaciosa para mayor libertad de movimiento, plantilla extraíble y lavable para personalizar la comodidad. Suela de goma antideslizante y resistente al desgaste. Perfectas para la oficina, el fin de semana o entrenamientos ligeros.', '71vTMfQfOoL._AC_SY695_.jpg', 'activo', 189.9, 27, 'Hombres', 'Calzado', 'Beige', '38, 39, 40, 41, 42', 109.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (51, 'Calzado Azul', 'Zapatos casuales de hombre, cómodos, ligeros y transpirables, perfectos para el verano y el uso diario. Parte superior de punto que permite la ventilación, suela de EVA y plantilla de espuma viscoelástica que absorbe impactos y proporciona amortiguación. Diseño con cordones, cuello elástico y lengüeta trasera para fácil colocación y protección del talón. Estilo casual y semiformal, ideal tanto para oficina como para ocasiones casuales.', '81z0Bt6erVL._AC_SY575_.jpg', 'activo', 199.9, 12, 'Hombres', 'Calzado', 'Azul', '38, 39, 40, 41, 42', 121.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (52, 'Calzado Blanco Negro', 'Zapatillas casuales versátiles para hombre, cómodas y transpirables, ideales para el uso diario. Diseño con cordones ajustables para un calce personalizado, perforaciones que permiten la ventilación y entresuela acolchada que brinda soporte en cada paso. Suela de goma antideslizante y resistente al desgaste para mayor durabilidad. Perfectas para completar cualquier look casual o semiformal.', '61CoFqjeGbL._AC_SY575_.jpg', 'activo', 209.9, 33, 'Hombres', 'Calzado', 'Blanco Negro', '38, 39, 40, 41, 42', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (53, 'Calzado Blanco', 'Zapatillas casuales para hombre, que combinan estilo, comodidad y ligereza. Parte superior con costuras acolchadas que ofrecen estabilidad y protección. Suela de goma ligera de 340 g (talla 9) resistente a resbalones y desgaste. Puntera espaciosa que permite libertad de movimiento, plantilla extraíble y lavable para personalizar la comodidad. Diseño con cordones, perfecto para looks relajados o actividades ligeras.', '61OOMN7fMIL._AC_SY695_.jpg', 'activo', 219.9, 36, 'Hombres', 'Calzado', 'Blanco', '38, 39, 40, 41, 42', 139.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (54, 'Calzado  Negro', 'Zapatillas casuales de hombre: combinan estilo y comodidad con parte superior acolchada que brinda estabilidad y protección. Ultraligeras (340 g, talla 9) con suela de goma resistente a resbalones y desgaste. Puntera espaciosa para libertad de movimiento y plantilla extraíble y lavable para mayor confort. Diseño con cordones, perfectas para looks relajados, paseos informales o entrenamientos ligeros.', '61rR+Zb4XWL._AC_SY575_.jpg', 'activo', 229.9, 21, 'Hombres', 'Calzado', ' Negro', '38, 39, 40, 41, 42', 149.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (55, 'Calzado  Blanco Negro', 'Zapatillas retro de hombre, combinan estilo clásico y moderno con parte superior de cuero PU suave y gamuza para una estética elegante y minimalista. Construcción transpirable con malla que mantiene los pies frescos, forro de tela suave y plantilla de felpa para máxima comodidad. Suela desgastada que brinda tracción confiable y un toque visual único. Versátiles para looks casuales o deportivos.', '71URxQVHQEL._AC_SY575_.jpg', 'activo', 259.9, 25, 'Hombres', 'Calzado', ' Blanco/Negro', '38, 39, 40, 41, 42', 179.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (56, 'Calzado Blanco Gris Negro', 'Zapatillas retro de hombre: combinan estilo clásico y moderno con parte superior de cuero PU suave y gamuza para un look elegante y minimalista. Construcción transpirable con malla que mantiene los pies frescos, forro de tela suave y plantilla de felpa que ofrece comodidad todo el día. Suela desgastada para tracción confiable y diseño visual único. Versátiles para cualquier ocasión, casual o deportiva.', '71lWmfzJpWL._AC_SY575_.jpg', 'activo', 279.9, 12, 'Hombres', 'Calzado', 'Blanco/Gris/Negro', '38, 39, 40, 41, 42', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (57, 'Calzado Marrón Claro', 'Oxford casuales slip-on para hombre: fáciles de poner, ligeros y transpirables. Parte superior de piel flexible y elástica que ofrece comodidad y ventilación natural. Suela atlética que mejora la tracción y la durabilidad, ideal para caminar con estabilidad y confianza. Versátiles para uso diario, combinan con vaqueros o pantalones deportivos para un look informal y cómodo.', '81mq8Y7CJwL._AC_SY575_.jpg', 'activo', 249.9, 14, 'Hombres', 'Calzado', 'Marrón Claro', '38, 39, 40, 41, 42', 159.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (58, 'Gorra Azul Denim Oscuro', 'Gorra en sarga de algodón con cierre ajustable de metal detrás. Cinta antisudor de algodón.

', 'a4979911885e37763b15d1d866e0a3d70fe9993d.avif', 'activo', 99, 25, 'Hombres', 'Accesorios', 'Azul denim oscuro/Amarillo, Liso', ' Única / Ajustable', 74.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (59, 'Gorros Azul', 'Gorro beanie en punto acanalado suave con aplicación pequeña de tela en la vuelta.

', '5746a342f58abfbcd3160ef6cecc9b33f6b5cec7.avif', 'activo', 86.8, 30, 'Hombres', 'Accesorios', 'Azul/Blanco, Soho NY, Liso', ' Única / Ajustable', 55, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (60, 'Gorra Negro', 'Gorra en sarga de algodón con motivo bordado delante. Modelo con visera plana, ojales bordados y cierre ajustable de plástico detrás.', '8c232e15ee93dd9acb40b6eda27be07e832ef201.avif', 'activo', 105.9, 28, 'Hombres', 'Accesorios', 'Negro/Blanco, NYC', ' Única / Ajustable', 79.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (61, 'Gafas Negro', 'Gafas de sol estilo piloto con montura y patillas de metal. Lentes polarizadas de color con protección UV. Plaquetas nasales ajustables. Las lentes polarizadas ofrecen una mayor nitidez de los colores y un mejor contraste al tiempo que eliminan los reflejos.

', '0cd7098867c152338f2f6a6cbcfe72f54c3be81f.avif', 'activo', 134.9, 15, 'Hombres', 'Accesorios', 'Negro, Liso', ' Única / Ajustable', 94.99, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (62, 'Cinturón Negro', 'Cinturón de piel con hebilla de metal.

', '99bc1d0739c5c0933984d1a2f8616a460414d269.avif', 'activo', 156.9, 14, 'Hombres', 'Accesorios', 'Negro', ' Única / Ajustable', 109.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (63, 'Collares Plateado', 'Collares en cadena barbada de metal con cierre de gatillo.

', '2202633730be24bcb57aa9c3faafb8af4c9c9091.avif', 'activo', 244.3, 29, 'Hombres', 'Accesorios', 'Plateado, Liso', ' Cadena: Largo: 46 cm', 193.2, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (64, 'Maletín Negro', 'Maletín en tejido suave, con dos asas revestidas, cremallera superior y dos compartimentos exteriores con cierre. Incluye correa bandolera ajustable y extraíble con herrajes de metal. Forrado, práctico y elegante, ideal para el trabajo o uso diario.', 'e5ff1606e428ea6758564f84e6961bc1a686bc2b.avif', 'activo', 285, 19, 'Hombres', 'Accesorios', 'Negro', ' Única ', 219.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (65, 'Guantes Marrón', 'Guantes tejido cepillado suave con puños de canalé de mezcla de lana. Forrados.

', '952787984918f37fc1780c21f57e83fbacf0ac06.avif', 'activo', 105.3, 27, 'Hombres', 'Accesorios', 'Marrón, Liso', 'S / M', 79.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (66, 'Gafas Rojo Vivo', 'Gafas de sol de deporte con montura y patillas de policarbonato resistente a impactos y golpes. Lentes teñidas de plástico con protección UV.

', 'cbf4de4f63b2931910315dd7d1387f24aecb54ef.avif', 'activo', 229.9, 20, 'Hombres', 'Accesorios', 'Rojo vivo, Liso', ' Única / Ajustable', 169.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (67, 'Corbata Azul Marino', 'Corbata clásica de tela. Ancho en la parte inferior 7 cm.

', '258a3c6f9b94481e212475bac13044d4ba501e70.avif', 'activo', 34.9, 21, 'Hombres', 'Accesorios', 'Azul marino, Liso', ' Largo 145 cm – Ancho 7 cm', 24.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (68, 'Bolso Gris Claro', 'Inspirado en los códigos deportivos clásicos, este bolso está confeccionado en nailon de color gris con una cremallera plateada que aporta contraste. Ha sido diseñado con una forma redondeada y espaciosa con dos asas de mano, una correa de hombro ajustable y un bolsillo en el interior para los objetos de valor. Cierre de cremallera Alto: 22 cm; Largo: 39 cm; Ancho: 17 cm', 'aaab12361eb976387a94bd7538940687cf359b81.avif', 'activo', 259.9, 12, 'Hombres', 'Accesorios', 'Gris Claro', ' Única ', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (69, 'Antifaz Negro', 'Antifaz acolchado en lyocell suave con tira elástica y cierre autoadherente detrás.

', '9ef62213b3c217e8777d30d20ff7a4bc2429087b.avif', 'activo', 49.9, 25, 'Hombres', 'Accesorios', 'Negro', ' Única ', 32.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (70, 'Blusas Crema', 'Blusa oversize en tejido transparente con detalles bordados. Modelo con cuello, cierre de bucle con botones delante y mangas globo largas con abertura y botón en los puños. Bajo redondeado con aberturas laterales.

', '6481f538a73e1f42e6e4669bae0d1ff4c9314d87.avif', 'activo', 179.9, 24, 'Mujeres', 'Blusas', 'Crema, Liso', 'XS, S, M, L, XL, XXL', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (71, 'Blusas Amarillo Claro', 'Blusa en tejido arrugado con cuello mao y botones revestidos delante. Mangas globo tres cuartos con ribete en los puños y bajo ligeramente redondeado.

', '2240dba65139f1e7ff776bf2beda2f9f0a091ca6.avif', 'activo', 149.9, 12, 'Mujeres', 'Blusas', 'Amarillo claro, Liso', 'XS, S, M, L, XL, XXL', 109.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (72, 'Blusas Blanco', 'Blusa en tejido arrugado con cuello mao y botones revestidos delante. Mangas globo tres cuartos con ribete en los puños y bajo ligeramente redondeado.

', 'c8a25433d7edf79bfff0ce69bbee0ef5999648b6.avif', 'activo', 149.9, 25, 'Mujeres', 'Blusas', 'Blanco, Liso', 'XS, S, M, L, XL, XXL', 119.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (73, 'Blusas Marrón Oscuro', 'Blusa corta en mezcla de viscosa. Modelo con escote en V pronunciado, cintura nido de abeja y mangas cortas abullonadas con ribetes de volante.

', '14c4842309fc886411c9a3828f121493cac2462b.avif', 'activo', 139.9, 11, 'Mujeres', 'Blusas', 'Marrón oscuro, Liso', 'XS, S, M, L, XL, XXL', 99.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (74, 'Blusas Azul Claro', 'Blusa en tejido vaporoso de mezcla de lino. Modelo entallado con cuello redondo, cierre de botones y mangas globo tres cuartos con puños elásticos.

', '8a3d9c0cb20b38a3e1e5ffab6ac81797d0b004a4.avif', 'activo', 169.9, 12, 'Mujeres', 'Blusas', 'Azul claro/Blanco, Rayas', 'XS, S, M, L, XL, XXL', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (75, 'Blusas Marrón Negro', 'Blusa en tejido vaporoso de mezcla de lino. Modelo entallado con cuello redondo, cierre de botones y mangas globo tres cuartos con puños elásticos.

', '4d782ff29b2d3d1a3566590a5dd2e9b20e870c51.avif', 'activo', 169.9, 13, 'Mujeres', 'Blusas', 'Marrón/Negro, Estampado de leopardo', 'XS, S, M, L, XL, XXL', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (76, 'Blusas Rosa', 'Blusa en tejido vaporoso de mezcla de lino y viscosa. Modelo con escote redondo, cierre de botones y mangas globo tres cuartos con puños elásticos.

', '48001aee91a10ee3c5f039be2d209b7e8574358a.avif', 'activo', 179.9, 27, 'Mujeres', 'Blusas', 'Rosa, Liso', 'XS, S, M, L, XL, XXL', 139.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (77, 'Blusas Blanco', 'Blusa en tejido vaporoso de algodón, con ribetes de picot, cuello redondo y abertura en V con lazada fina. Mangas globo largas con elástico en las muñecas y puños acampanados. Presenta costura fruncida en la cintura con ribete de encaje y peplum con vuelo, aportando un estilo femenino y delicado.', 'e4d809a008d62678175960ebc14afda5bb8367a1.avif', 'activo', 219.9, 29, 'Mujeres', 'Blusas', 'Blanco, Liso', 'XS, S, M, L, XL, XXL', 169.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (78, 'Vestidos Rojo Vivo', 'Vestido bandeau con cuerpo acorsetado de sarga, con almohadillas de cadera y costuras moldeadoras reforzadas que crean una silueta tipo reloj de arena. Cuenta con cremallera oculta y cierre de corchete en la espalda, además de cinturilla interna de grosgrain ajustable para mayor soporte. Presenta costura fruncida bajo la cadera para un efecto layering y falda globo de maxivolumen en mezcla de viscosa. Forro de algodón para mayor comodidad.', 'ed93931b89194d8ee9e685d06dbfad481e695c52.avif', 'activo', 499.9, 27, 'Mujeres', 'Vestidos', 'Rojo vivo, Liso', 'S,M,L,XL,XS', 359.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (79, 'Vestidos Negro Blanco Lunares', 'Vestido midi entallado en punto elástico. Modelo con escote barco, manga japonesa y cintura fruncida. Cuerpo forrado.

', '3ec1939b4be9a84c96ad34493eb0d1c34fcdaf70.avif', 'activo', 229.9, 15, 'Mujeres', 'Vestidos', 'Negro/Blanco, Lunares', 'S,M,L,XL,XS', 179.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (80, 'Vestidos Marrón Oscuro Blanco De Lunares', 'Vestido a media pierna en tejido ligero de viscosa, con tirantes finos ajustables y escote cuadrado. Cuerpo entallado con fruncido tipo nido de abeja y falda acampanada. Sin forro para una sensación ligera y fresca.', '490d11edf71dfcd390499c49daaac19eb024cc8d.avif', 'activo', 199.9, 17, 'Mujeres', 'Vestidos', 'Marrón oscuro/Blanco, De lunares', 'S,M,L,XL,XS', 149.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (81, 'Vestidos Verde Caqui', 'Vestido maxi sin mangas en tejido de malla, con cuello alto, costuras laterales fruncidas sobre las caderas para un efecto drapeado y falda suavemente acampanada. Parcialmente forrado para mayor comodidad.', 'edc3f8e87f76294b5d7d2f7dbf8140751f583fac.avif', 'activo', 249.9, 22, 'Mujeres', 'Vestidos', 'Verde caqui, Liso', 'S,M,L,XL,XS', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (82, 'Vestidos Negro Liso', 'Vestido midi sin mangas. Modelo con cuello redondo y costura fruncida en diagonal bajo la cintura. Cuerpo entallado en punto acanalado de algodón y falda con vuelo en tejido de mezcla de viscosa. Sin forrar.

', 'fe6c996ff2b064c886c5c7a55dc225dc705c5677.avif', 'activo', 219.9, 17, 'Mujeres', 'Vestidos', 'Negro, Liso', 'S,M,L,XL,XS', 169.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (83, 'Vestidos Marrón Azul Oscuro Blanco Rayas', 'Vestido evasé largo en popelina fresca de algodón con escote redondo y abertura en V con lazada. Mangas cortas abullonadas de corte raglán con remate elástico. Sin forro para una sensación de ligereza.

', 'af8d91a49501058d2e1ca68bb94e1708ae0e441b.avif', 'activo', 259.9, 11, 'Mujeres', 'Vestidos', 'Marrón/Azul oscuro/Blanco, Rayas', 'S,M,L,XL,XS', 199.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (84, 'Vestidos Crema Negro', 'Vestido tobillero con top largo de mezcla de viscosa y lino con ribetes en color de contraste. Falda en tejido de crepé para un look de superposiciones. Modelo con cuello redondo, cremallera oculta con cierre de corchete en la nuca y mangas cortas con dobladillo cosido vuelto. Falda con frunces en la parte superior para crear pliegues fluidos y bajo asimétrico. Forrada.

', '494c85a6bcbd9230a9aa301a8e7ea12cd1586fc3.avif', 'activo', 429.9, 24, 'Mujeres', 'Vestidos', 'Crema/Negro', 'S,M,L,XL,XS', 329.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (85, 'Vestidos Amarillo Claro Rosa Verde Floral', 'Vestido midi sin mangas en tejido fluido de satén con elegantes ribetes de encaje. Modelo de corte ajustado con escote de pico pronunciado, cremallera oculta en la espalda y copas fruncidas con inserción de encaje bajo el busto. Sin forrar.

', '1f5c0e7b4c056b6a4a0f46446b0fe32f70b4215d.avif', 'activo', 399.9, 27, 'Mujeres', 'Vestidos', 'Amarillo claro/Rosa/Verde, Floral', 'S,M,L,XL,XS', 299.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (86, 'Jean Negro Liso', 'Pantalón sastre en tejido de viscosa y algodón. Modelo de talle bajo con cierre de cremallera y botón y corchetes ocultos. Perneras globo maxivolumen con bolsillos al bies y bolsillos traseros insertados.

', 'fcd790fa5db43c6796f9b3ae81a61d48d5dd6f18.avif', 'activo', 259.9, 40, 'Mujeres', 'Pantalones', 'Negro, Liso', 'S,M,L,XL,XS', 199.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (87, 'Jean Beige Claro Liso', 'Vaquero tobillero de cinco bolsillos en denim con ligero stretch para una comodidad óptima. Modelo de pernera recta con cintura de talle alto y cierre de cremallera con botón. Corte ajustado de cadera a muslo, algo más ceñido en el bajo.

', 'd234ce610dab54386a9e8c9ba885879eeb6e0c6c.avif', 'activo', 219.9, 33, 'Mujeres', 'Pantalones', 'Beige claro, Liso', 'S,M,L,XL,XS', 169.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (88, 'Jean Azul Denim Claro Liso', 'Vaquero tobillero de cinco bolsillos en denim con ligero stretch para una comodidad óptima. Modelo de pernera recta con cintura de talle alto y cierre de cremallera con botón. Corte ajustado de cadera a muslo, algo más ceñido en el bajo.

', '4abf54b1fc726460eb94791c2572e1432d58cfff.avif', 'activo', 239.9, 36, 'Mujeres', 'Pantalones', 'Azul denim claro, Liso', 'S,M,L,XL,XS', 179.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (89, 'Jean Blanco Liso', 'Vaquero en denim de algodón con ligero stretch para una comodidad óptima. Perneras amplias con corte estándar de cintura a cadera y corte holgado de muslo a bajo. Modelo de talle alto con cierre de cremallera y botón de metal acanalado, bolsillos delanteros y traseros de parche, y raya delante y detrás. Largo estándar con bajo apenas apilado. Un vaquero de pernera ancha nunca puede faltar en tu fondo de armario.

', '0aa6c65e3b902e0682ce44fa2eb74d57a639c37f.avif', 'activo', 279.9, 33, 'Mujeres', 'Pantalones', 'Blanco, Liso', 'S,M,L,XL,XS', 219.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (90, 'Jean Marrón Oscuro Liso', 'Vaquero de cinco bolsillos en denim de algodón con ligero stretch para una comodidad óptima. Perneras amplias con corte estándar de cintura a cadera y corte holgado de muslo a bajo. Cintura de talle alto con cierre de cremallera y botón. Largo estándar con bajo apenas apilado.

', '81aefd8e5b96b02fcfd4cbd3b254304e1614b69d.avif', 'activo', 269.9, 22, 'Mujeres', 'Pantalones', 'Marrón oscuro, Liso', 'S,M,L,XL,XS', 209.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (91, 'Jean Gris Claro Jaspeado Liso', 'Vaquero de cinco bolsillos en denim de algodón rígido que se suaviza con el tiempo y el uso. Perneras rectas de corte holgado en cintura y cadera con estilo baggy de muslo a bajo. Cintura de talle alto con cierre de cremallera y botón. Largo estándar con bajo apenas apilado.

', 'a2422d953406e7132868c361ec4394674eedcdb4.avif', 'activo', 289.9, 26, 'Mujeres', 'Pantalones', 'Gris claro jaspeado, Liso', 'S,M,L,XL,XS', 219.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (92, 'Jean Negro Liso', 'Pantalón sastre en sarga suave con perneras amplias y raya delante y detrás. Modelo de talle alto con cierre de cremallera, botón oculto y corchete. Un bolsillo trasero y uno delantero decorativos, ambos insertados.

', '11b0d735be2e051556658157382a1a23e768320f.avif', 'activo', 269.9, 33, 'Mujeres', 'Pantalones', 'Negro, Liso', 'S,M,L,XL,XS', 209.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (93, 'Jean Azul Denim Liso', 'Vaquero tobillero de cinco bolsillos en denim de mezcla de algodón y viscosa con ligero stretch para una comodidad óptima. Perneras amplias con corte estándar de cintura a cadera y corte holgado de muslo a bajo. Cintura de talle alto con cierre de cremallera y botón.

', '1961bb5c7d534d4bebc7c76f0a92e50b7e52be7d.avif', 'activo', 279.9, 30, 'Mujeres', 'Pantalones', 'Azul denim, Liso', 'S,M,L,XL,XS', 219.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (94, 'Calzado Marrón Oscuro', 'Sandalias con acabado cepillado suave. Modelo con tira ancha, puntera redondeada y plantillas preformadas.

', '8a3513c6f3777593e5d427575dea4d51668ab4be.avif', 'activo', 179.9, 39, 'Mujeres', 'Calzado', 'Marrón oscuro, Liso', '38, 39, 40, 41, 42', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (95, 'Calzado Blanco Gris', 'Zapatillas deportivas en malla y tejido revestido con cierre de cordones y trabilla detrás. Forro y plantillas de malla. Suelas gruesas con diseño.

', '9df9b4dc60e88dbb8dc1addd7deef63a3cdd2a64.avif', 'activo', 249.9, 22, 'Mujeres', 'Calzado', 'Blanco/Gris', '38, 39, 40, 41, 42', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (96, 'Calzado Marrón Oscuro Gris Claro Plateado Blanco', 'Zapatillas deportivas en malla y tejido revestido con cierre de cordones y trabilla detrás. Forro y plantillas de malla. Suelas gruesas con diseño.

', 'a424a5a052f4a7567b6e73de962fb94ad6d8dde8.avif', 'activo', 239.9, 25, 'Mujeres', 'Calzado', 'Marrón oscuro/Gris claro/Plateado/Blanco', '38, 39, 40, 41, 42', 179.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (97, 'Calzado Beige Marrón Oscuro', 'Bailarinas estilo merceditas en paja de plástico trenzada con puntera redondeada y trabilla detrás. Tira fina ajustable sobre el empeine con hebilla de metal.

', 'd97e19264ddc901c680980b69c7505df6cb96f87.avif', 'activo', 179.9, 35, 'Mujeres', 'Calzado', 'Beige/Marrón oscuro', '38, 39, 40, 41, 42', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (98, 'Calzado Marrón', 'Sandalias de dedo en ante. Modelo con tira en T, puntera redonda y pulsera con lateral elástico. Tacón kitten.

', '9a61bcd16f74206e6ac0981ad513815ae24c9e1e.avif', 'activo', 229.9, 26, 'Mujeres', 'Calzado', 'Marrón', '38, 39, 40, 41, 42', 169.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (99, 'Calzado Marrón', 'Mules penny con acabado cepillado suave. Modelo estilo mocasín con puntera oblicua y costura de mocasín delante. Forro de punto.

', '07bd53d73344848022fee8b134c3ba954612f742.avif', 'activo', 199.9, 37, 'Mujeres', 'Calzado', 'Marrón', '38, 39, 40, 41, 42', 149.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (100, 'Calzado Beige', 'Sandalias cómodas estilo casual con doble tira ajustable y hebillas metálicas. Diseño en acabado cepillado suave ideal para uso diario y look relajado.
', '374375b545c12049655f6816bfb43a767fe46186.avif', 'activo', 129.9, 44, 'Mujeres', 'Calzado', 'Beige', '38, 39, 40, 41, 42', 169.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (101, 'Calzado Beige Claro Marrón Oscuro Bloques De Color', 'Zapatillas deportivas con cordones y trabilla detrás. Forro y plantillas de malla.

', '2d41aeb7596b09b772e4c78ee6f0d7d97253da1a.avif', 'activo', 239.9, 37, 'Mujeres', 'Calzado', 'Beige claro/Marrón oscuro, Bloques de color', '38, 39, 40, 41, 42', 179.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (102, 'Aros Dorado Liso', 'Pendientes de aro de plástico con acabado metalizado brillante.

', '2d2408f2cf8d39e53ec51de60cde2a0df2ccbd5f.avif', 'activo', 49.9, 25, 'Mujeres', 'Accesorios', 'Dorado, Liso', ' Única ', 34.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (103, 'Gafas Marrón Oscuro Amarillo Estampado De Carey', 'Gafas de sol con montura y lentes de plástico. Lentes teñidas con protección UV.

', '232bcaa00cd3cb64edf57116978a275d568a7fec.avif', 'activo', 129.9, 12, 'Mujeres', 'Accesorios', 'Marrón oscuro/Amarillo, Estampado de carey', ' Única ', 89.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (104, 'Pañuelo Azul Blanco Estampado Paisley', 'Pañuelo cuadrado con acabado desflecado. Confeccionado en tejido estampado de algodón con efecto denim lavado.

', '4705cc9b52e240cecc1a70e7a7ac5c3a840a3d13.avif', 'activo', 39.9, 21, 'Mujeres', 'Accesorios', 'Azul/Blanco, Estampado paisley', ' Única ', 59.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (105, 'Gafas Rosa', 'Gafas de sol de deporte con montura y patillas de policarbonato resistente a impactos y golpes. Lentes teñidas de plástico con protección UV.

', '6b3da742903128e735744170b1f3a2012ba431b6.avif', 'activo', 259.9, 14, 'Mujeres', 'Accesorios', 'Rosa, Liso', ' Única ', 199.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (106, 'Scrunchies Elásticos Gris Oscuro Beige Claro Estampado', 'Scrunchies elásticos en diseños variados.

', '0f297a1020599a3d7cf5ea71eab01d77cc64a3e3.avif', 'activo', 19.9, 19, 'Mujeres', 'Accesorios', 'Gris oscuro/Beige claro, Estampado', ' Única ', 29.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (107, 'Riñonera Rosa Empolvado Liso', 'Riñonera para correr con bolsillo de cremallera y detalle reflectante delante. Correa elástica ajustable con hebilla de plástico.

', 'a898333ebaeceb905f0bb0eb14ced28899a80c3f.avif', 'activo', 119.9, 30, 'Mujeres', 'Accesorios', 'Rosa empolvado, Liso', ' Única / Ajustable', 89.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (108, 'Casquete Topo Dorado Liso', 'Casquete en punto de viscosa efecto crochet con hilos brillantes en la trama.

', '3a7439f81f8c2565efa0cf62d8dd2b6492c72f6c.avif', 'activo', 119.9, 18, 'Mujeres', 'Accesorios', 'Topo/Dorado, Liso', ' Única ', 89.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (109, 'Cinturón Marrón Liso', 'Cinturón con hebilla de metal.

', 'b0255cce6558c582e1983e5daaa72eea9f978534.avif', 'activo', 159.9, 14, 'Mujeres', 'Accesorios', 'Marrón, Liso', ' Única / Ajustable', 119.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (110, 'Bolso Beige Claro Liso', 'Bolso con asa metálica gruesa y cierre magnético oculto arriba. Forrado.

', 'c4f1b2fc1679d0667de2f9500606b8ebc10692ad.avif', 'activo', 329.9, 18, 'Mujeres', 'Accesorios', 'Beige claro, Liso', ' Única ', 249.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (111, 'Gorra Rojo Oscuro Blanco', 'Gorra en sarga de algodón con efecto lavado y motivo bordado delante. Botón redondeado en la parte superior, cinta antisudor de algodón y trabilla ajustable con cierre de metal detrás.

', '95ac2560bf71dee33ea4e897c5c6f44e75ed9276.avif', 'activo', 129.9, 22, 'Mujeres', 'Accesorios', 'Rojo oscuro/Blanco, L.A. Athletic California', ' Única / Ajustable', 89.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (112, 'Abanico Blanco', 'Abanico plegable confeccionado en plástico y encaje delicado, con un remache metálico en la base que asegura la estructura. Ideal como accesorio de moda o para eventos elegantes.', '16a990a92b507c01edad1c62229a70d2488fee9b.avif', 'activo', 149.9, 24, 'Mujeres', 'Accesorios', 'Blanco, Liso', ' Única ', 109.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (113, 'Bolso De Hombro Burdeos', 'Bolso de hombro en tejido revestido con cremallera arriba. Asa ajustable con un extremo extralargo, y un compartimento exterior con solapa y cierre metálico. Forrado.

', '4f05b4d9ab27e2c3804f3424c98575d310739e3b.avif', 'activo', 339.9, 31, 'Mujeres', 'Accesorios', 'Burdeos, Liso', ' Única ', 269.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (114, 'Camiseta Verde Claro Negro Blanco', 'Camiseta de corte holgado confeccionada en punto suave de algodón estampado. Modelo con cuello redondo ribeteado en canalé y hombros caídos para un look cómodo y moderno. Ideal para uso diario y casual.', '7ef2796f215848049cbd030f60a4dee0a0c2bd20.avif', 'activo', 89.9, 20, 'Niños', 'Niños', 'Verde claro/Negro/Blanco, Too sweet to be sour, Corazón de manzana', '2-3 4-5 6-7 8-9 10-11 12-13', 69.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (115, 'Conjunto Azul', 'Conjunto formado por camiseta en punto suave de algodón y pantalón corto en tejido sudadera con interior cepillado suave.', '61348541b561a73b35f6ceb1bef5e3bbcbd240e5.avif', 'activo', 179.9, 23, 'Niños', 'Niños', 'Azul, San Diego sports club', '2-3 4-5 6-7 8-9 10-11', 139.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (116, 'Pantalón Beige Claro Negro Rayas', 'Pantalón en punto texturizado con cierre decorativo y cintura elástica con cordón de ajuste. Bolsillos al bies y bolsillo trasero abierto.

', '29b77cbed70bda909014928b6027990d24c8a752.avif', 'activo', 159.9, 30, 'Niños', 'Niños', 'Beige claro/Negro, Rayas', '2-3 4-5 6-7 8-9 10-11', 119.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (117, 'Joggers Cargo Verde Caqui Claro Liso', 'Joggers cargo en sarga de algodón con perneras rectas y corte holgado en cadera y muslo. Modelo con cinturilla elástica ajustable, cierre decorativo, bolsillos al bies, bolsillos traseros abiertos y bolsillos de parche en las perneras.

', 'bac5827aeef893819e95e7acd5378103d3160e18.avif', 'activo', 239.9, 21, 'Niños', 'Niños', 'Verde caqui claro, Liso', '2-3 4-5 6-7 8-9 10-11', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (118, 'Chaqueta  Verde Azul Marino', 'Chaqueta en tejido sudadera con parches bordados. Modelo con cuello de canalé, botones de presión delante y bolsillos laterales insertados. Ribete ancho de canalé en puños y bajo. Interior cepillado suave.

', 'fb8bc4bbab3441fbadfac04a6de8b9a31b62e0e7.avif', 'activo', 329.9, 26, 'Niños', 'Niños', 'Verde/Azul marino/Crema/Rojo, Peanuts, S, Snoopy, Snoopy', '2-3 4-5 6-7 8-9 10-11', 249.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (119, 'Pantalón Azul Denim Claro Liso', 'Pantalón de corte holgado en sarga de algodón con cierre decorativo y cintura elástica con cordón de ajuste. Bolsillos al bies, bolsillos traseros abiertos y perneras rectas, algo más estrechas en el bajo.

', 'bce69210820f113760e37e74ead9f0a415aebffa.avif', 'activo', 249.9, 25, 'Niños', 'Niños', 'Azul denim claro, Liso', '2-3 4-5 6-7 8-9 10-11', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (120, 'Camisa Beige Claro Negro Rayas', 'Camisa de manga corta en punto pointelle suave. Modelo de corte holgado con cuello abierto y botones delante.

', '35cbbd74182eb568b037e4c48a650478d8e3d15a.avif', 'activo', 119.9, 28, 'Niños', 'Niños', 'Beige claro/Negro, Rayas', '2-3 4-5 6-7 8-9 10-11', 89.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (121, 'Pantalón Marrón Liso', 'Pantalón de corte holgado en tejido vaporoso de mezcla de algodón y lino. Cintura elástica con cordón de ajuste, bolsillos al bies, bolsillo trasero de parche y perneras pitillo.

', 'b48ef7fc03f12298d4a73a19d0ccd41fe3372f2c.avif', 'activo', 249.9, 28, 'Niños', 'Niños', 'Marrón, Liso', '2-3 4-5 6-7 8-9 10-11', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (123, 'Cazadora Clásica Azul Denim', 'Cazadora clásica en denim de algodón suave con cuello inglés y botones de presión delante y en los puños. Bolsillos superiores decorativos con solapa y botón de presión.

', '62c9812acf130173af981b845a5952e8dfad67af.avif', 'activo', 319.9, 30, 'Niños', 'Niñas', 'Azul denim, Liso', '2-3 4-5 6-7 8-9 10-11', 249.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (124, 'Conjunto Rojo Blanco Floral', 'Conjunto de dos piezas en sirsaca de algodón vaporoso. Top con tirantes finos y escote cuadrado con abertura de cerradura y botones. Ribete de volante en escote, sisas y bajo. Pantalón con cintura elástica y perneras de corte holgado con ribete de volante en los bajos.

', '334ae0850600aa467b89802779cd4394838704ce.avif', 'activo', 289.9, 24, 'Niños', 'Niñas', 'Rojo/Blanco, Floral', '2-3 4-5 6-7 8-9 10-11', 219.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (125, 'Vestidos Azul Blanco Rayas', 'Vestido sin mangas en punto estilo sirsaca con cuello redondo y abertura de cerradura con botón en la espalda. Costura fruncida en la cintura con maxilazo cosido delante y falda acampanada.

', '4657d3bfbb3ade176a08b5dbeea32d55bbb7a7b2.avif', 'activo', 239.9, 27, 'Niños', 'Niñas', 'Azul/Blanco, Rayas', '2-3 4-5 6-7 8-9 10-11', 179.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (126, 'Falda Vaquera Azul Denim', 'Falda de cinco bolsillos en denim de algodón lavado. Modelo con elástico revestido en la parte posterior de la pretina y elástico oculto delante para un ajuste perfecto. Cierre de cremallera con botón.

', '6ae5946dbf84a42c384ce61aebff5c1da6d4b49b.avif', 'activo', 209.9, 22, 'Niños', 'Niñas', 'Azul denim', '2-3 4-5 6-7 8-9 10-11', 159.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (127, 'Vestidos Azul Claro Fresas', 'Vestido en tejido vaporoso de sirsaca de algodón. Modelo con cuello redondo, botones delante y mangas cortas raglán. Falda con fruncido escalonado para dar un toque de volumen a la prenda. Sin forrar.

', 'b50f1fe47d7ab5f401b407a3a48a11ee4b649b17.avif', 'activo', 249.9, 26, 'Niños', 'Niñas', 'Azul claro/Fresas', '2-3 4-5 6-7 8-9 10-11', 189.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (128, 'Camiseta Crema', 'Camiseta en punto suave de algodón. Modelo de manga corta con motivo estampado delante y cuello redondo.

', 'a4faf7504c72220d629fb4d6079381b17c7d3d35.avif', 'activo', 95, 24, 'Niños', 'Niñas', 'Crema/Hello Kitty', '2-3 4-5 6-7 8-9 10-11', 130, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (129, 'Camiseta Estampada Crema', 'Camiseta de manga larga en punto de algodón suave. Modelo con estampado, hombros caídos y cuello redondo ribeteado.

', '8764cda616649648afaecc2f12de1af515d19162.avif', 'activo', 119.9, 35, 'Niños', 'Niñas', 'Crema/Hello Kitty', '2-3 4-5 6-7 8-9 10-11', 89.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (130, 'Mono Crema Floral rojo', 'Mono en tejido vaporoso de algodón con tirantes elásticos de volante. Modelo con cuerpo nido de abeja, escote recto con ribete de volante y perneras largas de corte holgado.

', '753b95d5bf990374592d294622588645a8138bfa.avif', 'activo', 269.9, 28, 'Niños', 'Niñas', 'Crema/Floral rojo', '2-3 4-5 6-7 8-9 10-11', 209.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (131, 'Conjunto Beige Rayas Verdes', 'Conjunto de dos piezas formado por una ranita en lino suave y un body en punto suave de algodón. Ranita con escote cuadrado y tirantes ajustables con botón que se cruzan en la espalda. Elástico revestido suave en cintura y perneras. Body de manga corta con cuello redondo y abertura con botones de presión en un hombro (excepto en tallas 98–104) y en la entrepierna para facilitar el cambio de pañal. La colección H&M Adorables ofrece una cuidadosa selección de prendas atemporales de calidad con un confort excepcional.

', '2796dcefcb774550fe81cbbfdb1cf5efaf805b49.avif', 'activo', 169.9, 32, 'Niños', 'Bebés', 'Beige/Rayas verdes', '2–4 meses 4–6 meses 6–9 meses 9–12 meses 12–18 meses 18–24 meses', 129.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (132, 'Vestidos Rosa Claro Cuadros', 'Vestido en tejido suave de algodón de alta calidad con inserciones de encaje y body cosido. Modelo con cuello redondo, volantes sobrehilados delante que continúan por hombros y espalda, y abertura con botones detrás. Cintura fruncida y falda acampanada con bajo festoneado. Body con botones de presión en la entrepierna y elástico revestido fino alrededor de las perneras. La colección H&M Adorables ofrece una cuidadosa selección de prendas atemporales de calidad con un confort excepcional.', 'eb1aa14fc87da9add5afe4ca93a08d4dde96aae3.avif', 'activo', 31.9, 26, 'Niños', 'Bebés', 'Rosa claro/Cuadros', '2–4 meses 4–6 meses  6–9 meses 9–12 meses', 39.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (133, 'Patucos Beige Claro', 'Patucos para bebé con cordón de ajuste fino en el tobillo y caña plegable en canalé, confeccionados en lana suave al tacto, con regulación natural de temperatura y confort excepcional. Parte de la colección premium H&M Adorables.', '26e65e3fd013fd66c185f9b8d61abb3a26d80455.avif', 'activo', 92, 27, 'Niños', 'Bebés', 'Beige claro', ' Única / Ajustable', 104, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (134, 'Conjunto Beige Claro Floral', 'Conjunto de dos piezas de la colección H&M Adorables confeccionado en punto pointelle suave de algodón de alta calidad con mezcla de lyocell. Incluye un body de manga larga con frente cruzado, cierre de botones de presión y lazos, además de dos hileras de botones de presión en la entrepierna para ajustar el largo y cambiar el pañal fácilmente. Completan el conjunto unos leggings con cintura elástica revestida. El tejido es de alto gramaje, lo que brinda mayor grosor, durabilidad y comodidad.', '5fe62dfc1ccc2020c0ae0c0c96fb4a788bc75286.avif', 'activo', 115, 26, 'Niños', 'Bebés', 'Beige claro/Floral', '2–4 meses 4–6 meses  6–9 meses 9–12 meses', 130, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (135, 'Pack Beige Floral', 'Bodies de manga corta confeccionados en punto acanalado suave de algodón de alta calidad. Cuentan con un diseño cruzado y botones de presión en los laterales y en la entrepierna para facilitar el cambio de pañal. Las costuras fruncidas en las perneras aseguran un ajuste cómodo y seguro. El tejido de alto gramaje aporta mayor grosor y durabilidad sin comprometer la comodidad. Parte de la colección H&M Adorables, diseñada para ofrece', '259d34c04b63643eada9a54cb8d6437aed35ff66.avif', 'activo', 39.9, 29, 'Niños', 'Bebés', 'Beige/Floral', '2-4 meses  4–6 meses  6–9 meses  9–12 meses ', 31.92, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (136, 'Conjunto Blanco Floral', 'Conjunto de dos piezas en algodón de alta calidad. Camiseta de manga corta en punto suave. Modelo con detalle bordado delante y ribete de popelina en el cuello que continúa por un hombro e incorpora botones para facilitar el vestido. Pantalón corto en popelina vaporosa con cinturilla elástica ajustable y ribete de volante con acabado sobrehilado en los bajos. La colección H&M Adorables ofrece una cuidadosa selección de prendas atemporales de calidad con un confort excepcional.

', '0c5956113885e9db15ec9da4dfd3df0454064671.avif', 'activo', 39.9, 20, 'Niños', 'Bebés', 'Blanco/Floral', '2–4 meses 4–6 meses 6–9 meses  9–12 meses ', 50, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (137, 'Merceditas Crema', 'Merceditas bordadas en lona de algodón con sección en yute trenzado en la puntera. Tira sobre el empeine con cierre autoadherente y trabilla de grosgrain detrás. Forro de algodón y plantillas de Cellfit™, una espuma técnica de alto rendimiento que ofrece una comodidad óptima. Suela contorneada en yute trenzado.

', '13f425675d642c5c85536bc6979aacd03f0950a0.avif', 'activo', 83, 30, 'Niños', 'Calzado', 'Crema', '2-3 4-5 6-7 ', 94, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (138, 'Mocasines Azul Marino', 'Mocasines en tejido cepillado con tira penny decorativa y costura tradicional delante. Forro de punto y plantillas de espuma técnica para una comodidad óptima.

', '1f6cd8c5c3d91050a2849ee90f92a923628da059.avif', 'activo', 69, 31, 'Niños', 'Calzado', 'Azul marino', '2-3 4-5 6-7 ', 55, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (139, 'Alpargatas Beige Claro', 'Alpargatas con puntera redondeada, tira elástica sobre el empeine y trabilla detrás. Forro de lona y ribete en yute trenzado alrededor de la suela. Plantillas acolchadas y suelas flexibles para una comodidad óptima.

', '3578bc62f922a2d499915d512330bbb8f1b6cfd8.avif', 'activo', 79, 32, 'Niños', 'Calzado', 'Beige claro', '2-3 4-5 6-7 ', 99, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (140, 'Zapatillas Beige Estampado De Leopardo', 'Zapatillas deportivas con cierre autoadherente, cordones elásticos y collarín y lengüeta ligeramente acolchados. Trabilla de grosgrain detrás. Forro de malla y plantillas de espuma técnica para una comodidad óptima. Suelas con diseño.

', 'd49e618919736753ba65ce6cd823f460148b3713.avif', 'activo', 84.9, 33, 'Niños', 'Calzado', 'Beige/Estampado de leopardo', '2-3 4-5 6-7 ', 99.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (141, 'Printed Trainers Beige Cómics de Marvel', 'Zapatillas deportivas estampadas confeccionadas en tejido recubierto, con cordones elásticos, cierre autoadherente delante, collarín y lengüeta ligeramente acolchados, y trabilla de grosgrain detrás para ponerlas y quitarlas más fácil. Tienen forro de piqué y plantillas de espuma técnica Cellfit™ para confort óptimo, además de suelas con diseño que aportan tracción y estilo.', '0eaf6b2b48ba643abb1a843d0de897d54287b0e2.avif', 'activo', 95, 34, 'Niños', 'Calzado', 'Beige/Cómics de Marvel', '2-3 4-5 6-7 ', 105, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (142, 'Conjunto Azul', 'Conjunto de dos piezas en tejido sudadera ligero con estampado. Camiseta de corte relajado con hombros marcadamente caídos, mangas cortas y remate de canalé en cuello y bajo. Pantalón corto con cintura elástica, cordón de ajuste y bolsillos laterales discretos.

', '8e7a4582b5f26903cac329550f0aa900d5805b49.avif', 'activo', 49.9, 34, 'Niños', 'Deportivo', 'Azul/Spiderman', '2–4 meses  4–6 meses  6–9 meses 9–12 meses ', 59.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (143, 'Conjunto Azul Oscuro', 'Conjunto estampado de dos piezas en punto suave de algodón. Camiseta con cuello ribeteado en canalé. Pantalón corto con cintura elástica.

', '14895118cad90f5796daae127968114483894c3e.avif', 'activo', 39.9, 34, 'Niños', 'Deportivo', 'Azul oscuro/Snoopy', '2–4 meses  4–6 meses  6–9 meses 9–12 meses', 49.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (144, 'Conjunto Amarillo Claro', 'Conjunto de fútbol en tejido funcional de secado rápido para absorber el sudor y mantener el frescor durante la práctica deportiva. Camiseta estampada con cuello redondo ribeteado en canalé y mangas raglán cortas. Pantalón corto con cintura elástica, cordón de ajuste y motivos estampados en las perneras.

', 'cb70fabf0e774ee8fb2b1c23ce4a84fc3cda57e2.avif', 'activo', 79.9, 35, 'Niños', 'Deportivo', 'Amarillo Claro Pokémon', '2-3 4-5 6-7 ', 90, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (145, 'Conjunto Rojo', 'Conjunto de fútbol en tejido funcional de secado rápido para absorber el sudor y mantener el frescor durante la práctica deportiva. Camiseta estampada con cuello redondo ribeteado en canalé y mangas raglán cortas. Pantalón corto con cintura elástica, cordón de ajuste y motivos estampados en las perneras.', '1cf979a6b2a3853b904f429eb41a23109ef2dcc7.avif', 'activo', 105, 37, 'Niños', 'Deportivo', 'Rojo Hot Wheels', '2-3 4-5 6-7 ', 130, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (146, 'Conjunto Negro', 'Conjunto de fútbol en tejido funcional de secado rápido para absorber el sudor y mantener el frescor durante la práctica deportiva. Camiseta estampada con cuello redondo ribeteado en canalé y mangas raglán cortas. Pantalón corto con cintura elástica, cordón de ajuste y motivos estampados en las perneras.', '0c7b4db32d032da240015ae0bb7273aa0827bb26.avif', 'activo', 30.9, 39, 'Niños', 'Deportivo', 'Negro Spiderman', '2-3 4-5 6-7 ', 55.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (147, 'Conjunto Azul Vivo', 'Conjunto de fútbol en tejido funcional de secado rápido para absorber el sudor y mantener el frescor durante la práctica deportiva. Camiseta estampada con cuello redondo ribeteado en canalé y mangas raglán cortas. Pantalón corto con cintura elástica, cordón de ajuste y motivos estampados en las perneras.', 'f190991ce5b5f92b01da848a30f8c22f46701daa.avif', 'activo', 64.9, 37, 'Niños', 'Deportivo', 'Azul vivo/Lilo y Stitch', '2-3 4-5 6-7 ', 95, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (148, 'Gorras Rojo', 'Gorra en sarga de algodón con cierre ajustable de metal detrás. Cinta antisudor de algodón.

', 'd12e24e26e5755972c90d5f36aeec29d1ceb6489.avif', 'activo', 30, 39, 'Otros', 'Gorras', 'Rojo', ' Única / Ajustable', 45, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (149, 'Gorras Topo', 'Gorra en sarga de algodón con cierre ajustable de metal detrás. Cinta antisudor de algodón.

', '7f85cf54f045dffb7627b4cb13f431d644b598ec.avif', 'activo', 55, 22, 'Otros', 'Gorras', 'Topo', ' Única / Ajustable', 70, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (150, 'Gorras  Gris Oscuro', 'Gorra de correr en nailon con paneles laterales de malla para una ventilación óptima. Cordón de ajuste reflectante detrás con tensor de plástico.

', '4727a5cf3cf6bb5f066aa54dcf4a954ed10ce00c.avif', 'activo', 35, 21, 'Otros', 'Gorras', 'Gris Oscuro', ' Única / Ajustable', 70, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (151, 'Gorras Dark brown', 'Gorra trucker en sarga de algodón y malla con aplicación bordada delante y botón revestido arriba. Hebilla ajustable de plástico detrás. Cinta antisudor de algodón.

', '4aca506efc339ffce33bafbf66315c6f94651ca0.avif', 'activo', 20, 24, 'Otros', 'Gorras', 'Dark brown International 94 Crew', ' Única / Ajustable', 35, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (152, 'Gorras Óxido Lavado', 'Una gorra de béisbol desgastada de seis paneles confeccionada en lona de algodón con una forma suave e inestructurada. Diseñada con una visera precurvada, ojales metálicos y una correa de velcro ajustable en la parte trasera para un ajuste personalizado.

', '9429874a19ad1a33dbba973b218b9fa49d824cf3.avif', 'activo', 70, 23, 'Otros', 'Gorras', 'Óxido lavado', ' Única / Ajustable', 100, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (153, 'Gorras Verde', 'Gorra en sarga de algodón con motivo bordado delante, ojales bordados arriba y trabilla ajustable con hebilla de metal detrás. Cinta antisudor de algodón.

', '2941c83147f3456751c8bdf13e3e1941cfa50349.avif', 'activo', 100, 24, 'Otros', 'Gorras', 'Verde C', ' Única / Ajustable', 160, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (154, 'Gorras Azul', 'Gorra en sarga de algodón con cinta antisudor de algodón. Trabilla ajustable y cierre de metal detrás.

', '45d2644c9eb0c6c54e169a4a6856e0fca6aa4056.avif', 'activo', 160, 25, 'Otros', 'Gorras', 'Azul Run wild', ' Única / Ajustable', 230, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (155, 'Gorras Crema', 'Gorra en sarga de algodón con motivo decorativo delante y ojales bordados. Cinta antisudor de algodón y trabilla ajustable con cierre de metal detrás.

', 'cf6229ad4c7a1f765b35f9c83dc836bff7f7f241.avif', 'activo', 19.99, 26, 'Otros', 'Gorras', 'Crema Creative Director', ' Única / Ajustable', 29.9, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (156, 'Zapatos Marrón', 'Zapatos náuticos en ante suave con lazada, costura de mocasín con frunces delante y cordones decorativos en los laterales y detrás. Forro en sarga de algodón y plantillas de piel.

', 'b24566ebc482b7b0e13c24de0994cbdda8a25c3f.avif', 'activo', 25, 25, 'Otros', 'Zapatos', 'Marrón', '38, 39, 40, 41, 42', 50, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (157, 'Zapataos Beige Claro', 'Zapatillas deportivas con cordones y trabilla detrás. Forro y plantillas de malla.


', '2d41aeb7596b09b772e4c78ee6f0d7d97253da1a.avif', 'activo', 60, 26, 'Otros', 'Zapatos', 'Beige claro', '38, 39, 40, 41, 42', 90, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (158, 'Zapatos Blanco Azul Marino', 'Zapatillas deportivas con diseño en bloques de color, cordones y lengüeta ligeramente acolchada. Forro de malla. Suelas de goma con diseño.

', '3b82dfb2f504d5d6b2d389cf9f0c259c1fdc7d41.avif', 'activo', 90, 28, 'Otros', 'Zapatos', 'Blanco/Azul marino', '38, 39, 40, 41, 42', 140, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (159, 'Zapatos Negro', 'Zapatillas deportivas con collarín y lengüeta ligeramente acolchados, cierre autoadherente delante y trabilla de grosgrain detrás. Forro y plantillas en malla suave. Suelas con diseño.

', 'cd423b82196af17e0c32dea3c68b3146d4f4ec7f.avif', 'activo', 140, 29, 'Otros', 'Zapatos', 'Negro', '38, 39, 40, 41, 42', 250, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (160, 'Zapatos Rojo Bloques De Color', 'Zapatillas deportivas con collarín acolchado, lengüeta y cordones. Suelas con diseño.

', '24f03215b21739add42705a3d3341e120819152e.avif', 'activo', 300, 25, 'Otros', 'Zapatos', 'Rojo Bloques de color', '38, 39, 40, 41, 42', 500, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (161, 'Zapatos Verde', 'Zapatillas deportivas en lona de algodón con cordones. Forro y plantillas de lona. Suelas de goma con diseño.

', '641e23cdedf9d390f7cf94becb13ce064eca4d1d.avif', 'activo', 50, 29, 'Otros', 'Zapatos', 'Verde', '38, 39, 40, 41, 42', 80, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (162, 'Zapatos Negro Bloques De Color', 'Zapatillas deportivas con collarín acolchado, lengüeta y cordones. Suelas con diseño.

', 'ad8f4d082b596fa866f7578000bac3f4ca64f7e4.avif', 'activo', 80, 28, 'Otros', 'Zapatos', 'Negro Bloques De Color', '38, 39, 40, 41, 42', 120, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (163, 'Medias Blanco', 'Leotardos en punto fino de mezcla de algodón suave. Cintura elástica.

', 'ef86b632f93a910072a9bb25228fd9043096da6f.avif', 'activo', 9, 20, 'Otros', 'Medias', 'Blanco ', ' Única ', 15, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (164, 'Medias Beige Jaspeado', 'Leotardos en punto fino de mezcla de algodón suave. Cintura elástica.

', '3a52bca859fe39825f3e2e837ec4b5d9747ea1d6.avif', 'activo', 16, 22, 'Otros', 'Medias', 'Beige Jaspeado', ' Única ', 25, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (165, 'Medias Lila Claro Rosa Claro', 'Leotardos en punto fino de mezcla de algodón suave. Cintura elástica.

', '16571a58dd90f7e56159d24a7da3678b223e0215.avif', 'activo', 26, 27, 'Otros', 'Medias', 'Lila claro Rosa claro', ' Única ', 40, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (166, 'Medias Rosa Claro', 'Leotardos en punto fino de mezcla de algodón suave. Cintura elástica.

', 'b6c32e507cc3a6383b554e95d9c246b56306e013.avif', 'activo', 41, 33, 'Otros', 'Medias', 'Rosa claro Corazones', ' Única ', 65, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (167, 'Medias Negro', 'Medias finas con cintura elástica.

', '4aa53baaa1fd9fe027dd2c57cb51ccef63f6bad0.avif', 'activo', 66, 29, 'Otros', 'Medias', 'Negro', ' Única ', 120, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (168, 'Bragas Verde Claro Blanco', 'Bragas en punto de algodón con ribetes finos de encaje. Modelo de cintura media con refuerzo interior y parte trasera semicubriente.

', '5e87d35cf36cfe107be006055d292a6bb0f286b6.avif', 'activo', 6, 41, 'Otros', 'Ropa Interior', 'Verde claro Blanco', 'S,M,L,XL,XS', 12, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (169, 'Bragas Negro', 'Bragas en punto de algodón con ribetes finos de encaje. Modelo de cintura media con refuerzo interior y parte trasera semicubriente.

', '4c374844d3652d0c7f4e5d8b7a375dc858064b86.avif', 'activo', 13, 40, 'Otros', 'Ropa Interior', 'Negro', 'S,M,L,XL,X', 25, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (170, 'Sujetador Negro', 'Sujetador de deporte en tejido funcional confeccionado con SoftMove™, que brinda la máxima suavidad, comodidad y sujeción, y DryMove™, que ayuda a absorber el sudor. Modelo de tirantes con escote redondo y copas forradas con relleno extraíble que moldean el busto y proporcionan un buen ajuste. Elástico revestido en el bajo. Sujeción media para ejercicio de intensidad moderada.

', 'e05c7c5aacb8fb77d3b71c4eab498a52f7724187.avif', 'activo', 26, 42, 'Otros', 'Ropa Interior', 'Negro', 'S,M,L,XL,XS', 40, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (171, 'Sujetador Beige Jaspeado', 'Sujetadores de lactancia suaves en punto de algodón. Modelo con tirantes ajustables y copas acolchadas con abertura y espacio para los discos de lactancia. Cierre de corchetes en la espalda. Sin aros.

', '6415ef382b3998fdabec216fd33bb1727d20f794.avif', 'activo', 41, 42, 'Otros', 'Ropa Interior', 'Beige jaspeado Rosa claro', 'S,M,L,XL,XS', 70, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (172, 'Bufandas Rosa', 'Bufanda triangular en punto de musgo suave.

', '1439f375214e5fa585fd351c666ab3f08969d902.avif', 'activo', 15, 43, 'Otros', 'Bufandas', 'Rosa', ' Única ', 25, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (173, 'Bufandas Gris Jaspeado', 'Bufanda en punto de musgo suave con extremos en punta.

', '45743b901f107250c7a1272386e938f731592071.avif', 'activo', 26, 44, 'Otros', 'Bufandas', 'Gris Jaspeado', ' Única ', 40, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (174, 'Bufandas Beige', 'Bufanda con acabado cepillado suave. Flecos en los extremos y acabado desflecado en los laterales.


', 'd33773290274516233a51c411fc0a0d12b68818c.avif', 'activo', 41, 45, 'Otros', 'Bufandas', 'Beige', ' Única ', 60, TRUE);
INSERT INTO productos (id_producto, nombre, descripcion, foto, estado, precio, cantidad_stock, categoria, subcategoria, colores, tallas, "precioAnterior", "esNuevo") VALUES (175, 'Bufandas Rojo Oscuro', 'Esta suave bufanda se ha diseñado con idea de llevarla drapeada o anudada sobre los hombros y añadir calidez y dinamismo a cualquier look. Confeccionada en pura lana, se le ha dado forma de triángulo de generosas dimensiones. 130 cm x 47 cm/51,2" x 18,5"

', '6f3d139ee900bb63d6aa7cae8a8328f1a8772ee3.avif', 'activo', 61, 47, 'Otros', 'Bufandas', 'Rojo oscuro', ' Única ', 90, TRUE);
SELECT setval('productos_id_producto_seq', (SELECT MAX(id_producto) FROM productos));

-- USUARIOS
TRUNCATE TABLE usuarios RESTART IDENTITY CASCADE;
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (1, 'Andres munoz', 'andresm@gmail.com', 'bcrypt_sha256$$2b$12$VEhuw5Lzbq./rfpMyQM0XuiVrFWNvGvD7yPNbrXzvMv93xYGz9ARO', 'activo', FALSE, FALSE, 2, '2026-03-19 19:34:36.457504');
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (2, 'andres romero', 'andres@gmail.com', 'bcrypt_sha256$$2b$12$OEzELAApUR1k54yN8vjxD.NyQ0HVBuFxDoREAw2g0cuIU243I.REy', 'activo', FALSE, FALSE, 2, '2026-04-18 02:10:53.180255');
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (3, 'camilo cruz', 'camilo@gmail.com', 'bcrypt_sha256$$2b$12$TsQvn7wbXD6C488qwfdmeuuVC6Mk9XFXwceszskQN72VZy3w4MouG', 'activo', FALSE, FALSE, 2, NULL);
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (4, 'Test', 'test@test.com', 'bcrypt_sha256$$2b$12$GIhCCOIwRHWXjVND5gs08e38y5BFHXMTYGBprmMtbJIkBdYmx8/hO', 'activo', FALSE, FALSE, NULL, '2026-03-19 17:18:09.091974');
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (5, 'heidy', 'heidy@gmail.com', 'bcrypt_sha256$$2b$12$6UtU8oX.aEUbMvs.kEgcpuWhyBXGMNSmbS4AsCrWZzHZk8VBAGx0W', 'activo', FALSE, FALSE, 2, '2026-03-19 18:20:07.932799');
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (6, 'joel', 'joel@email.com', 'bcrypt_sha256$$2b$12$psLai6iZE5/rDI900CZs2.ngG12ScAKGG5EBmu.YrdZTtSHYyuWwO', 'activo', FALSE, FALSE, 2, '2026-03-24 18:51:05.623005');
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (7, 'Admin', 'admin@oksu.com', 'bcrypt_sha256$$2b$12$0SLbCnjTSXpPzY5SeIWmX.Me8Ta42qAEWiJIimfZBlUzIUngKgLxy', 'activo', TRUE, TRUE, 1, '2026-05-30 15:09:07.276904');
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (8, 'Samuel', 'samuel@email.com', 'bcrypt_sha256$$2b$12$g4ta7cNDaeHBVFc3Zmu5RuAAFbm4/N2p4W8eQncL3PBGadXSxJ/ne', 'activo', FALSE, FALSE, 2, '2026-03-29 15:02:07.204306');
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (9, 'Heidy', 'hei@gmail.com', 'bcrypt_sha256$$2b$12$zrgr.mA1IgosyfLSIvyCHeWBmRaeixpUP0cr3d8CQXSX8k6iR0D2K', 'activo', FALSE, FALSE, 2, '2026-04-18 02:25:55.373589');
INSERT INTO usuarios (id_usuario, nombre, email, contrasena, estado, is_staff, is_superuser, id_rol, last_login) VALUES (10, 'camilo', 'cam@gmail.com', 'bcrypt_sha256$$2b$12$/wGU0AsMoox.sw68Y3ySFOgK8650QTkbgoGn8xCdRvqMDCY0Ditmq', 'activo', FALSE, FALSE, 2, '2026-04-18 02:35:50.477842');
SELECT setval('usuarios_id_usuario_seq', (SELECT MAX(id_usuario) FROM usuarios));

-- CLIENTES
TRUNCATE TABLE clientes RESTART IDENTITY CASCADE;
INSERT INTO clientes (id_cliente, nombre, telefono, email, contrasena, estado) VALUES (1, 'Heidy', NULL, 'hei@gmail.com', 'bcrypt_sha256$$2b$12$zrgr.mA1IgosyfLSIvyCHeWBmRaeixpUP0cr3d8CQXSX8k6iR0D2K', 'activo');
INSERT INTO clientes (id_cliente, nombre, telefono, email, contrasena, estado) VALUES (2, 'camilo', NULL, 'cam@gmail.com', 'bcrypt_sha256$$2b$12$/wGU0AsMoox.sw68Y3ySFOgK8650QTkbgoGn8xCdRvqMDCY0Ditmq', 'activo');
SELECT setval('clientes_id_cliente_seq', (SELECT MAX(id_cliente) FROM clientes));

-- VENTAS
TRUNCATE TABLE ventas RESTART IDENTITY CASCADE;
INSERT INTO ventas (id_venta, fecha_venta, total_venta, estado, metodo_pago, id_cliente) VALUES (1, '2026-04-18 02:33:03.275447', 10354.7, 'completada', 'pse', 1);
INSERT INTO ventas (id_venta, fecha_venta, total_venta, estado, metodo_pago, id_cliente) VALUES (2, '2026-04-18 02:36:52.646859', 10799.6, 'completada', 'pse', 2);
SELECT setval('ventas_id_venta_seq', (SELECT MAX(id_venta) FROM ventas));

-- DETALLE_VENTAS
TRUNCATE TABLE detalle_ventas RESTART IDENTITY CASCADE;
INSERT INTO detalle_ventas (id_detalle, cantidad, precio_unit, subtotal, id_producto, id_venta) VALUES (1, 1, 99.9, 99.9, 9, 1);
INSERT INTO detalle_ventas (id_detalle, cantidad, precio_unit, subtotal, id_producto, id_venta) VALUES (2, 1, 124.9, 124.9, 10, 1);
INSERT INTO detalle_ventas (id_detalle, cantidad, precio_unit, subtotal, id_producto, id_venta) VALUES (3, 1, 129.9, 129.9, 11, 1);
INSERT INTO detalle_ventas (id_detalle, cantidad, precio_unit, subtotal, id_producto, id_venta) VALUES (4, 1, 129.9, 129.9, 11, 2);
INSERT INTO detalle_ventas (id_detalle, cantidad, precio_unit, subtotal, id_producto, id_venta) VALUES (5, 1, 149.9, 149.9, 72, 2);
INSERT INTO detalle_ventas (id_detalle, cantidad, precio_unit, subtotal, id_producto, id_venta) VALUES (6, 1, 239.9, 239.9, 96, 2);
INSERT INTO detalle_ventas (id_detalle, cantidad, precio_unit, subtotal, id_producto, id_venta) VALUES (7, 1, 259.9, 259.9, 86, 2);
INSERT INTO detalle_ventas (id_detalle, cantidad, precio_unit, subtotal, id_producto, id_venta) VALUES (8, 1, 20, 20, 151, 2);
SELECT setval('detalle_ventas_id_detalle_seq', (SELECT MAX(id_detalle) FROM detalle_ventas));

-- Reactivar FK checks
SET session_replication_role = DEFAULT;

-- FIN DEL SCRIPT