# Generated by Django 4.2.29 on 2026-03-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(db_column='contrasena', max_length=100)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
