# Generated by Django 4.2.29 on 2026-03-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True},
        ),
    ]
